name: Simple Android Build

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --no-daemon --stacktrace

      # ðŸ§± Build debug APK only on develop branch
      - name: Build debug APK
        if: github.ref == 'refs/heads/develop'
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Upload debug APK
        if: github.ref == 'refs/heads/develop'
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: '**/build/outputs/**/*.apk'

      - name: Decode keystore
        if: github.ref == 'refs/heads/master'
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > keystore.jks
          ls -l keystore.jks
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Build signed release APK
        if: github.ref == 'refs/heads/master'
        env:
          ANDROID_KEYSTORE_PATH: keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease --no-daemon --stacktrace
